-- =============================================================
-- 表名：mes_produce_report_sheet（MES生产报工同步表）
-- 数据库：MySQL 8
-- 来源：生产报工接口 data[] 响应记录
-- 说明：一行对应一个上游报工 sheetId，保存报工、产出、质检、入库和扩展生产属性
-- =============================================================

CREATE TABLE `mes_produce_report_sheet` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sheet_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '上游报工ID，对应sheetId',
  `org_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '机构ID，对应orgId',
  `produce_task_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '生产任务ID，对应produceTaskId',
  `produce_work_order_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '生产工单ID，对应produceWorkOrderId',
  `task_no` varchar(128) NOT NULL DEFAULT '' COMMENT '任务号，对应taskNo',
  `batch_no` varchar(128) NOT NULL DEFAULT '' COMMENT '批次号，对应batchNo',
  `sheet_batch_no` varchar(128) NOT NULL DEFAULT '' COMMENT '完工批次号，对应sheetBatchNo',
  `shift_sheet_no` varchar(128) NOT NULL DEFAULT '' COMMENT '物料批次，对应shiftSheetNo',
  `document_code` varchar(128) NOT NULL DEFAULT '' COMMENT '单据编码，对应documentCode',

  `shift_id` varchar(64) NOT NULL DEFAULT '' COMMENT '班次ID，对应shiftId',
  `shift_name` varchar(128) NOT NULL DEFAULT '' COMMENT '班次名称，对应shiftName',
  `shift_alias` varchar(128) NOT NULL DEFAULT '' COMMENT '班次别名，对应shiftAlias',
  `course_id` varchar(64) NOT NULL DEFAULT '' COMMENT '班组ID，对应courseId',
  `course_name` varchar(128) NOT NULL DEFAULT '' COMMENT '班组名称，对应courseName',
  `course_alias` varchar(128) NOT NULL DEFAULT '' COMMENT '班组别名，对应courseAlias',
  `factory_area_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '工作单元ID，对应factoryAreaId',
  `factory_area_name` varchar(128) NOT NULL DEFAULT '' COMMENT '工作单元名称，对应factoryAreaName',
  `factory_area_alias` varchar(128) NOT NULL DEFAULT '' COMMENT '工作单元别名，对应factoryAreaAlias',
  `task_factory_area_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '任务工厂单元ID，对应taskFactoryAreaId',
  `task_factory_area_name` varchar(128) NOT NULL DEFAULT '' COMMENT '任务工厂单元名称，对应taskFactoryAreaName',
  `org_position_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '机构岗位ID，对应orgPositionId',

  `material_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '产出物料ID，对应materialId',
  `produce_code` varchar(128) NOT NULL DEFAULT '' COMMENT '产品编码，对应produceCode',
  `produce_name` varchar(256) NOT NULL DEFAULT '' COMMENT '产品名称，对应produceName',
  `produce_measure_unit` varchar(64) NOT NULL DEFAULT '' COMMENT '产品计量单位，对应produceMeasureUnit',
  `product_paper_type` varchar(128) NOT NULL DEFAULT '' COMMENT '产品纸种，对应productPaperType',
  `output_type` tinyint(4) NOT NULL DEFAULT 0 COMMENT '产出类型，对应outputType',
  `output` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '实际产出数量，对应output',
  `wet_output` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '湿重，对应wetOutput',
  `wet_weight` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '报工湿重，对应wetWeight',
  `weigh_output` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '称重重量，对应weighOutput',
  `tare` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '皮重，对应tare',
  `loss_amount` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '损耗数量，对应lossAmount',
  `loss_reason_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '损耗原因ID，对应lossReasonId',
  `init_grade_material_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '初定级物料ID，对应initGradeMaterialId',
  `init_grade_quantity` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '初定级物料数量，对应initGradeQuantity',

  `send_date` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '报工日期，对应sendDate',
  `sheet_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '报工时间，对应sheetTime',
  `receipt_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '单据日期，对应receiptTime',
  `produce_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '生产日期，对应produceTime',
  `main_send_date` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '主车间日期，对应mainSendDate',
  `slitting_date` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '分切日期，对应slittingDate',
  `sheet_batch_begin_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '完工批次开始时间，对应sheetBatchBeginTime',
  `sheet_batch_end_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '完工批次结束时间，对应sheetBatchEndTime',

  `status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '完工状态：1-完工，2-退回，对应status',
  `sheet_flag` tinyint(4) NOT NULL DEFAULT 1 COMMENT '报工标识：1-正常报工，2-异常报工，对应sheetFlag',
  `sheet_type` varchar(64) NOT NULL DEFAULT '' COMMENT '完工类型，对应sheetType',
  `stop_task_flag` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否结束生产任务：0-否，1-是，对应stopTaskFlag',
  `part_sheet_flag` tinyint(4) NOT NULL DEFAULT 0 COMMENT '部分报工标识，对应partSheetFlag',
  `issued_type` tinyint(4) NOT NULL DEFAULT 0 COMMENT '下发方式：1-工作中心，2-工作单元，对应issuedType',
  `source_type` tinyint(4) NOT NULL DEFAULT 1 COMMENT '报工来源：1-默认，2-自动完工，对应source',
  `data_source` tinyint(4) NOT NULL DEFAULT 0 COMMENT '数据来源：1-PC手工录入，2-PDA手工录入，3-称重，对应dataSource',
  `device_linkage` tinyint(4) NOT NULL DEFAULT 0 COMMENT '设备联动报工：0-其他，1-非联动手动，2-设备联动，对应deviceLinkage',
  `material_distribution_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'APP投料同报工关联物料投放ID，对应materialDistributionId',
  `associated_sheet_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '关联生产报工ID，对应associatedSheetId',

  `grade_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '等级ID，对应gradeId',
  `sheet_grade_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '质检前等级ID，对应sheetGradeId',
  `grade_reason` varchar(512) NOT NULL DEFAULT '' COMMENT '等级原因，对应gradeReason',
  `color_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '色号ID，对应colorId',
  `color_text` varchar(128) NOT NULL DEFAULT '' COMMENT '色号文本，对应colorText',
  `check_result` tinyint(4) NOT NULL DEFAULT -1 COMMENT '检验结果：-1-未检验，0-待定，1-不合格，2-合格，对应checkResult',
  `check_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '质检时间，对应checkTime',
  `check_finish` tinyint(4) NOT NULL DEFAULT 0 COMMENT '质检是否完成：0-未完成，1-不合格处理编辑，2-不合格处理已处理，对应checkFinish',
  `check_mode` varchar(64) NOT NULL DEFAULT '' COMMENT '检验模式或库位字段，对应checkMode',

  `entry_status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '入库状态，对应entryStatus',
  `entry_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '入库单ID，对应entryId',
  `store_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '完工入库库位ID，对应storeId',
  `store_name` varchar(128) NOT NULL DEFAULT '' COMMENT '库位名称，对应storeName',
  `store_code` varchar(64) NOT NULL DEFAULT '' COMMENT '库位编码，对应storeCode',
  `store_p_name` varchar(128) NOT NULL DEFAULT '' COMMENT '仓库名称，对应storePName',
  `store_p_code` varchar(64) NOT NULL DEFAULT '' COMMENT '仓库编码，对应storePCode',
  `location` varchar(256) NOT NULL DEFAULT '' COMMENT '仓库位置，对应location',
  `belong_company` varchar(256) NOT NULL DEFAULT '' COMMENT '仓库所属公司，对应belongCompany',
  `sheet_entry_remark` varchar(512) NOT NULL DEFAULT '' COMMENT '报工入库备注，对应sheetEntryRemark',
  `task_finish` tinyint(4) NOT NULL DEFAULT 0 COMMENT '任务完成状态，对应taskFinish',

  `range_wide` int(11) NOT NULL DEFAULT 0 COMMENT '幅宽，对应rangeWide',
  `speed` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '车速，对应speed',
  `quantitative` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '定量，对应quantitative',
  `length_value` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '长度，对应length',
  `gross_weight` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '毛重，对应grossWeight',
  `diam` decimal(22,6) NOT NULL DEFAULT 0.000000 COMMENT '直径，对应diam',
  `roll` varchar(128) NOT NULL DEFAULT '' COMMENT '母辊，对应roll',
  `container_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '容器ID，对应container',
  `roll_batch` varchar(128) NOT NULL DEFAULT '' COMMENT '母卷批次，对应rollBatch',
  `machine_no` int(11) NOT NULL DEFAULT 0 COMMENT '车次，对应machineNo',
  `out_paper_roll_no` varchar(128) NOT NULL DEFAULT '' COMMENT '外购纸卷编号，对应outPaperRollNo',
  `connector` int(11) NOT NULL DEFAULT 0 COMMENT '接头，对应connector',
  `paper_bind_num` varchar(128) NOT NULL DEFAULT '' COMMENT '原纸捆号，对应paperBindNum',
  `inkjet_code` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否喷码：0-不喷码，1-喷码，对应inkjetCode',
  `proposal_meter` int(11) NOT NULL DEFAULT 0 COMMENT '建议米数，对应proposalMeter',
  `rack_num` int(11) NOT NULL DEFAULT 0 COMMENT '退纸架号，对应rackNum',
  `slitting_course_group` varchar(128) NOT NULL DEFAULT '' COMMENT '分切班组，对应slittingCourseGroup',
  `large_roll_no` varchar(128) NOT NULL DEFAULT '' COMMENT '大卷辊号，对应largeRollNo',
  `paper_core` varchar(128) NOT NULL DEFAULT '' COMMENT '纸芯，对应paperCore',
  `paper_disease` varchar(512) NOT NULL DEFAULT '' COMMENT '纸病，对应paperDisease',
  `customer` varchar(256) NOT NULL DEFAULT '' COMMENT '客户，对应customer',

  `main_sheet_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '主车间报工ID，对应mainSheetId',
  `main_factory_area_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '主车间工厂单元ID，对应mainFactoryAreaId',
  `main_shift_id` varchar(64) NOT NULL DEFAULT '' COMMENT '主车间班次ID，对应mainShiftId',
  `main_course_id` varchar(64) NOT NULL DEFAULT '' COMMENT '主车间班组ID，对应mainCourseId',
  `qrcode_record_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '条码记录ID，对应qrcodeRecordId',
  `step_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '工步ID，对应stepId',
  `sabetsu` tinyint(4) NOT NULL DEFAULT -1 COMMENT '糟别：1-丢糟，2-面糟，3-红糟，4-小粮糟，5-大粮糟，6-湿糟，7-底糟，8-双轮底，9-混糟，10-酱香，11-清香，0-其他，对应sabetsu',
  `wine_barrel_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '酒桶ID，对应wineBarrelId',
  `tanker_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '罐车ID，对应tankerId',
  `standard_sequential_number` varchar(128) NOT NULL DEFAULT '' COMMENT '标准序号，对应standardSequentialNumber',
  `coding` varchar(128) NOT NULL DEFAULT '' COMMENT '编码，对应coding',
  `small_roll_number` varchar(128) NOT NULL DEFAULT '' COMMENT '小卷辊号，对应smallRollNumber',
  `execution_standard` varchar(256) NOT NULL DEFAULT '' COMMENT '执行标准，对应executionStandard',
  `user_name` varchar(128) NOT NULL DEFAULT '' COMMENT '用户名，对应userName',
  `template_name` varchar(128) NOT NULL DEFAULT '' COMMENT '模板名称，对应templateName',
  `note` varchar(1024) NOT NULL DEFAULT '' COMMENT '备注，对应note',

  `source_create_by` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '上游创建人，对应createBy',
  `source_create_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '上游创建时间，对应createTime',
  `source_create_time_ms` datetime(3) NOT NULL DEFAULT '1970-01-01 08:00:00.000' COMMENT '上游创建时间毫秒，对应createTimeMs',
  `source_modify_by` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '上游修改人，对应modifyBy',
  `source_modify_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '上游修改时间，对应modifyTime',
  `source_modify_time_ms` datetime(3) NOT NULL DEFAULT '1970-01-01 08:00:00.000' COMMENT '上游修改时间毫秒，对应modifyTimeMs',

  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '本表创建时间',
  `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '本表修改时间',
  `rec_status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '记录状态：1-有效，0-删除',
  `create_by` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '本表创建人ID',
  `modify_by` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '本表修改人ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MES生产报工同步表';
